#!/usr/bin/python2

import socket
import sys

try:
	host = sys.argv[1]
	port = sys.argv[2]
	payload = sys.argv[3]
	payload_source = open("modules/{0}".format(payload),"r").read().split("\n")[0]
	print(host+":"+port+":"+payload)
	print(payload_source)
except Exception as e:
	print("Usage: {0} TARGET_HOST PORT PAYLOAD_MODULE".format(sys.argv[0]))
	print(e)

def main():
	socket_ = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	try:
		socket_.connect((host, int(float(port))))
		socket_.sendall(payload_source.encode("utf-8"))
		data = socket_.recv(1024)
		socket_.close()
	except Exception as e:
		print("Exiting")
		print(e)
		exit()

if __name__ == "__main__":
	main()
